# Site settings
title: Fabiano Santos Florentino
description: 'Site Reliability Engineer'
url: 'https://florentino.codar.info'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Fabiano Santos Florentino'
  email: fabianoflorentino@outlook.com
  twitter_username: fabianosanflor
#   facebook_username: joshgerdes
  github_username: fabianoflorentino
  linkedin_username: fabianosantosflorentino

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: markdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
